use crate::comet::ir::{ExecutionGraph, ExecutionNode, OperatorOp};
use std::collections::HashMap;

pub struct Codegen;

impl Codegen {
    pub fn new() -> Self {
        Codegen
    }

    pub fn generate_library(&self, contexts: &Vec<crate::comet::synthesis::Context>) -> String {
        let mut code = String::new();
        
        // Header
        code.push_str("// Generated by Comet\n");
        code.push_str("use polars::prelude::*;\n");
        code.push_str("use std::collections::HashMap;\n");
        code.push_str("use crate::comet::runtime::*;\n\n");
        
        // Struct Definitions
        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str("pub struct StrategyMeta {\n");
        code.push_str("    pub variant_id: u32,\n");
        code.push_str("    pub tags: HashMap<String, String>,\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str("pub struct DataSpec {\n");
        code.push_str("    pub universe: Vec<String>,\n");
        code.push_str("}\n\n");

        // get_meta
        code.push_str("pub fn get_meta(variant_id: u32) -> StrategyMeta {\n");
        code.push_str("    let mut tags = HashMap::new();\n");
        code.push_str("    tags.insert(\"version\".to_string(), \"0.1\".to_string());\n");
        code.push_str("    StrategyMeta { variant_id, tags }\n");
        code.push_str("}\n\n");

        // select
        code.push_str("pub fn select(variant_id: u32) -> DataSpec {\n");
        code.push_str("    match variant_id {\n");
        for (i, ctx) in contexts.iter().enumerate() {
            let universe = self.extract_universe(&ctx.graph);
            let uni_str = universe.iter().map(|s| format!("\"{}\".to_string()", s)).collect::<Vec<String>>().join(", ");
            code.push_str(&format!("        {} => DataSpec {{ universe: vec![{}] }},\n", i, uni_str));
        }
        code.push_str("        _ => DataSpec { universe: vec![] },\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");

        // generate_all
        code.push_str("pub fn generate_all(variant_id: u32, inputs: &Inputs) -> (DataFrame, State) {\n");
        code.push_str("    match variant_id {\n");
        for (i, _) in contexts.iter().enumerate() {
            code.push_str(&format!("        {} => (execute_variant_{}(inputs), State::default()),\n", i, i));
        }
        code.push_str("        _ => (DataFrame::default(), State::default()),\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
        
        // generate (stub for now)
        code.push_str("pub fn generate(variant_id: u32, new_data: &Inputs, state: State) -> (DataFrame, State) {\n");
        code.push_str("    // Incremental not yet implemented, fallback to full calc stub or error\n");
        code.push_str("    generate_all(variant_id, new_data)\n");
        code.push_str("}\n\n");

        // Variant Executors
        for (i, ctx) in contexts.iter().enumerate() {
            code.push_str(&self.generate_variant_executor(i, &ctx.graph));
        }

        code
    }

    fn extract_universe(&self, graph: &ExecutionGraph) -> Vec<String> {
        let mut universe = Vec::new();
        for node in &graph.nodes {
            if let ExecutionNode::Source { name, .. } = node {
                universe.push(name.clone());
            }
        }
        universe
    }

    fn generate_variant_executor(&self, id: usize, graph: &ExecutionGraph) -> String {
        let mut code = String::new();
        code.push_str(&format!("fn execute_variant_{}(inputs: &Inputs) -> DataFrame {{\n", id));
        code.push_str("    let len = inputs.len();\n");
        code.push_str("    let num_timesteps = inputs.timesteps();\n\n");
        
        code.push_str("    // 1. Initialization Phase\n");
        for (node_id, node) in graph.nodes.iter().enumerate() {
            match node {
                ExecutionNode::Source { name, .. } => {
                    code.push_str(&format!("    let var_{}_ptr = inputs.get_ptr(\"{}\");\n", node_id, name));
                },
                ExecutionNode::Constant { value, .. } => {
                    code.push_str(&format!("    let var_{}_val = {};\n", node_id, value));
                },
                ExecutionNode::Operation { op, .. } => {
                    code.push_str(&format!("    let mut var_{}_out = vec![0.0f64; len];\n", node_id));
                    code.push_str(&format!("    let var_{}_out_ptr = var_{}_out.as_mut_ptr();\n", node_id, node_id));
                    
                    let func_name = match op {
                        OperatorOp::ZScore => "cs_zscore",
                        OperatorOp::Divide => "divide",
                        OperatorOp::Filter => "filter",
                        OperatorOp::UpdateWhen => "update_when",
                        OperatorOp::FunctionCall(f) => f.as_str(),
                        _ => "unknown",
                    }.to_lowercase();
                    
                    code.push_str(&format!("    let period = 10; // TODO: extract from AST constraints\n"));
                    code.push_str(&format!("    let state_{} = unsafe {{ comet_{}_init(period, len) }};\n", node_id, func_name));
                }
            }
        }
        
        code.push_str("\n    // 2. Event Loop Phase\n");
        code.push_str("    for t in 0..num_timesteps {\n");
        for (node_id, node) in graph.nodes.iter().enumerate() {
            if let ExecutionNode::Operation { op, args } = node {
                let func_name = match op {
                    OperatorOp::ZScore => "cs_zscore",
                    OperatorOp::Divide => "divide",
                    OperatorOp::FunctionCall(f) => f.as_str(),
                    _ => "unknown",
                }.to_lowercase();
                
                let mut arg_ptrs = Vec::new();
                for &arg_id in args {
                    // Rough mapping to pointers for the current timestep
                    arg_ptrs.push(format!("var_{}_ptr.add(t * len)", arg_id));
                }
                
                let args_str = arg_ptrs.join(", ");
                if args.len() == 1 {
                    code.push_str(&format!("        unsafe {{ comet_{}_step(state_{}, {}, var_{}_out_ptr, len) }};\n", func_name, node_id, args_str, node_id));
                } else if args.len() == 2 {
                    code.push_str(&format!("        unsafe {{ comet_{}_step(state_{}, {}, var_{}_out_ptr, len) }};\n", func_name, node_id, args_str, node_id));
                }
            }
        }
        code.push_str("    }\n\n");
        
        code.push_str("    // 3. Cleanup Phase\n");
        for (node_id, node) in graph.nodes.iter().enumerate() {
            if let ExecutionNode::Operation { op, .. } = node {
                let func_name = match op {
                    OperatorOp::ZScore => "cs_zscore",
                    OperatorOp::Divide => "divide",
                    OperatorOp::FunctionCall(f) => f.as_str(),
                    _ => "unknown",
                }.to_lowercase();
                code.push_str(&format!("    unsafe {{ comet_{}_free(state_{}) }};\n", func_name, node_id));
            }
        }
        
        if !graph.nodes.is_empty() {
             let last_id = graph.nodes.len() - 1;
             code.push_str(&format!("\n    // TODO: Convert var_{}_out to DataFrame\n", last_id));
             code.push_str("    DataFrame::default()\n");
        } else {
             code.push_str("    DataFrame::default()\n");
        }
        
        code.push_str("}\n\n");
        code
    }
}
