; ModuleID = 'test_module'
source_filename = "test_module"

; --- EXTERNAL DECLARATIONS ---
; These tell LLVM that these functions exist elsewhere (in our Rust stdlib).
; They will be resolved during the linking phase.

; malloc: Allocates memory of i64 bytes and returns an i8 pointer.
declare ptr @malloc(i64)

; free: Deallocates memory pointed to by an i8 pointer.
declare void @free(ptr)

; comet_cs_zscore_init: Allocates and initializes the operator state.
; Takes `period` (i64) and `len` (i64) as arguments. Returns a pointer to the state.
declare ptr @comet_cs_zscore_init(i64, i64)

; comet_cs_zscore_step: Executes one timestep of the z-score logic.
; Arguments: state ptr, input array ptr, output array ptr, len (i64).
declare void @comet_cs_zscore_step(ptr, ptr, ptr, i64)

; comet_cs_zscore_free: Cleans up the operator state.
declare void @comet_cs_zscore_free(ptr)

; (Serialization/Deserialization placeholders)
declare ptr @comet_cs_zscore_serialize(ptr)
declare ptr @comet_cs_zscore_deserialize(ptr)


; --- VARIANT EXECUTOR ---
; This is the main function generated by `Codegen::generate_variant_executor`.
; It executes a specific topological sequence of operators.

; Function Signature:
; @execute_variant_0(
;   ptr %0,  ; %0: Pointer to an array of input pointers (`double** inputs`). 
;   ptr %1,  ; %1: Pointer to the output stream array (`double* output`).
;   i64 %2,  ; %2: `len` (the size of each cross-sectional array slice).
;   i64 %3   ; %3: `timesteps` (the total number of loop iterations).
; )
define void @execute_variant_0(ptr %0, ptr %1, i64 %2, i64 %3) {

entry:
  ; 1. Initialization Phase & Memory Allocations

  ; Calculate the allocation size for the output buffers (len * 8 bytes for f64).
  %alloc_size = mul i64 %2, 8
  
  ; Get the pointer to the first input variable (index 0) from the `inputs` array.
  %input_gep_0 = getelementptr ptr, ptr %0, i64 0
  
  ; Dereference the pointer to get the actual `double*` input stream.
  %var_0_ptr = load ptr, ptr %input_gep_0, align 8
  
  ; Allocate intermediate memory for the output of the first operator (Node 1).
  %malloc_out_1 = call ptr @malloc(i64 %alloc_size)
  
  ; Initialize the state for the `cs_zscore` operator (Node 1). 
  ; Passes a stub `period=10` and the array `len` (%2).
  %state_1 = call ptr @comet_cs_zscore_init(i64 10, i64 %2)
  
  ; 2. Event Loop Setup
  ; Allocate a local variable `t` on the stack to hold the current timestep index.
  %t = alloca i64, align 8
  
  ; Initialize `t = 0`.
  store i64 0, ptr %t, align 4
  
  ; Jump to the loop condition check.
  br label %event_loop_cond

event_loop:                                       ; preds = %event_loop_cond
  ; 3. Event Loop Body
  
  ; Calculate the array offset for the current timestep: `t_val * len`
  ; IMPORTANT: This is the offset to the START of the sub-array for timestep `t`. 
  ; It effectively skips ahead `len` elements at a time. It is NOT the offset 
  ; of a single scalar item, but rather the offset of the entire cross-sectional "chunk"
  ; that corresponds to the current date/timestep.
  %offset = mul i64 %t_val, %2
  
  ; Calculate the start address of the input stream slice for this timestep.
  ; GEP (GetElementPtr) essentially does: stream_in_0 = &var_0_ptr[offset]
  %stream_in_0 = getelementptr double, ptr %var_0_ptr, i64 %offset
  
  ; Calculate the start address of the output stream slice for this timestep.
  %stream_out = getelementptr double, ptr %1, i64 %offset
  
  ; Execute the `cs_zscore` operator for this timestep.
  ; Passes: state ptr, input slice, output slice, len.
  call void @comet_cs_zscore_step(ptr %state_1, ptr %stream_in_0, ptr %stream_out, i64 %2)
  
  ; Jump to the loop increment block.
  br label %event_loop_inc

event_loop_inc:                                   ; preds = %event_loop
  ; 4. Event Loop Increment
  
  ; Compute `t_next = t_val + 1`.
  %t_next = add i64 %t_val, 1
  
  ; Store the incremented value back into the `t` stack variable.
  store i64 %t_next, ptr %t, align 4
  
  ; Jump back to the loop condition check.
  br label %event_loop_cond

event_loop_cond:                                  ; preds = %event_loop_inc, %entry
  ; 5. Event Loop Condition
  
  ; Load the current value of `t`.
  %t_val = load i64, ptr %t, align 4
  
  ; Compare `t_val < timesteps` (%3).
  %loop_cond = icmp ult i64 %t_val, %3
  
  ; If `loop_cond` is true (1), branch to %event_loop. 
  ; Otherwise (0), branch to %event_loop_end to clean up.
  br i1 %loop_cond, label %event_loop, label %event_loop_end

event_loop_end:                                   ; preds = %event_loop_cond
  ; 6. Cleanup Phase
  
  ; Call the free function for the `cs_zscore` operator state.
  ; Note: In a real graph with more intermediate `malloc` calls, 
  ; we would also inject `free(ptr)` calls here for `%malloc_out_1`.
  call void @comet_cs_zscore_free(ptr %state_1)
  
  ; Return from the executor.
  ret void
}
